"""empty message

Revision ID: 402df88bb03e
Revises: b2d8f185b0b9
Create Date: 2022-05-11 19:48:06.801149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402df88bb03e'
down_revision = 'b2d8f185b0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_invites',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('pet_id', 'reservation_id')
    )
    op.drop_constraint('reservations_pet_id_fkey', 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'pet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reservations_pet_id_fkey', 'reservations', 'pets', ['pet_id'], ['id'])
    op.drop_table('reservation_invites')
    # ### end Alembic commands ###
